columnSuffix: null
handle: textoRico
instructions: null
name: 'Texto rico'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  css: null
  defaultTransform: null
  fullGraphqlData: true
  headingLevels:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  js: null
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - heading
    - '|'
    - bold
    - italic
    - link
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
